FROM node:22-bookworm-slim
WORKDIR /app
COPY docker/22/start-container /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container
COPY package*.json ./
RUN npm ci
COPY . .
EXPOSE 30679
ENTRYPOINT ["start-container"]
